# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: partialzip
before:
  hooks:
    # you may remove this if you don't use vgo
    - make vendor
#     # you may remove this if you don't need go generate
#     - go generate ./...
builds:
  - main: ./cli/unzip
    binary: punzip
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64

checksum:
  name_template: "checksums.txt"

sign:
  artifacts: checksum

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
